export const FETCH_NEWEST_PRODUCT_REQUEST = "FETCH_NEWEST_PRODUCT_REQUEST";
export const FETCH_NEWEST_PRODUCT_SUCCESS = "FETCH_NEWEST_PRODUCT_SUCCESS";
export const FETCH_NEWEST_PRODUCT_FAILURE = "FETCH_NEWEST_PRODUCT_FAILURE";

export const FETCH_BANNER_REQUEST = "FETCH_BANNER_REQUEST";
export const FETCH_BANNER_SUCCESS = "FETCH_BANNER_SUCCESS";
export const FETCH_BANNER_FAILURE = "FETCH_BANNER_FAILURE";
